jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install Procursus
        uses: dhinakg/procursus-action@main
        with:
          packages: ldid findutils sed coreutils make

      - name: Install System Dependencies
        run: |
          brew update
          # Try installing choma from Homebrew if it exists (you can remove if it doesn't)
          brew install chroma || echo "choma not available via Homebrew"

      - name: Clone choma
        run: |
          git clone https://github.com/opa334/ChOma.git
          export CHOMA_INCLUDE="$(pwd)/ChOma/include"
          echo "CHOMA_INCLUDE=${CHOMA_INCLUDE}" >> $GITHUB_ENV

      - name: Build choma
        run: |
          cd ChOma
          make

      - name: Install THEOS (without SDKs)
        run: |
          set -x
          export BASEDIR="$(pwd)"
          export THEOS="${BASEDIR}/theos"
          mkdir -p $THEOS
          curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos >> install-theos.sh
          gsed -E "/^\s*get_theos\s*$/,+1 s/^(\s*)(get_sdks)\s*$/\1mkdir -p \${THEOS}\/sdks\n\1touch \${THEOS}\/sdks\/sdk\n\1\2/g" -i install-theos.sh
          bash install-theos.sh
          cd $BASEDIR

      - name: Set Environment Variables
        run: |
          set -x
          T2=$(TZ=UTC-2 date +'%Y%m%d_%H%M%S')
          TS=$(date -j -f "%Y%m%d_%H%M%S" "${T2}" +%s)
          SHASH=$(git rev-parse --short HEAD)
          echo "ctime=${T2}" >> $GITHUB_ENV
          echo "ctimestamp=${TS}" >> $GITHUB_ENV
          echo "shorthash=${SHASH}" >> $GITHUB_ENV

      - name: Build
        run: |
          set -x
          sudo security import Exploits/fastPath/arm.pfx -k /Library/Keychains/System.keychain -P password -A
          export BASEDIR="$(pwd)"
          export THEOS="${BASEDIR}/theos"
          export CFLAGS="-I${CHOMA_INCLUDE} -I/usr/include/xpc"
          export LDFLAGS="-framework XPC"
          chmod +x ./BaseBin/pack.sh
          gmake -j$(sysctl -n hw.physicalcpu)
          cp -a Dopamine/Dopamine.tipa Dopamine/Dopamine_${{ env.shorthash }}_${{ env.ctime }}.tipa
          cp -a Dopamine/Dopamine.tipa Dopamine/Dopamine_Latest.tipa

      - name: Upload Latest Artifact
        id: dopamine-latest-upload
        uses: actions/upload-artifact@main
        with:
          name: Dopamine_Latest
          path: |
            ${{ github.workspace }}/Dopamine/Dopamine_Latest.tipa

      - name: Upload Hashed Artifact
        id: dopamine-hashed-upload
        uses: actions/upload-artifact@main
        with:
          name: Dopamine_${{ env.shorthash }}_${{ env.ctime }}
          path: |
            ${{ github.workspace }}/Dopamine/Dopamine_${{ env.shorthash }}_${{ env.ctime }}.tipa
